### ISSUE TITLE
Mob Prevention

### ISSUE THREAD

**Issue by abused** [Maxwell-lt/MobBlocker#12]
Hi, so while playing with this mod i found a bug where slimes are not protected against, looking to add this mod in my modpack but i need it for the slime protection feature, if you can fix that it would be great 👍

**Comment by Maxwell-lt** [comment]
Sure, I can add that in.

**Comment by abused** [comment]
All right thanks, also my modpack is on the atlauncher meaning id like to as for permission to upload it on the ATLauncher to use in my pack since its ARR

**Comment by Maxwell-lt** [comment]
You have my permission to use this mod in your pack.

Just note that the mod is still in beta and will likely update fairly quickly.

**Comment by abused** [comment]
Yeah no worries
