### ISSUE TITLE
Visible protection field

### ISSUE THREAD

**Issue by Maxwell-lt** [Maxwell-lt/MobBlocker#26]
Add a visible mesh box (perhaps hexagons) outlining the area of protection. Similar type of render to the chunk overlay view. Pulse when a mob is teleported or a projectile is killed. Configurable colors, with the Chunk Protector's field color and the Area Protector's field color being configured separately.

**Comment by Davastating** [comment]
Any news on this feature? Maybe with enable/disable the overlay view on right-click.

**Comment by Maxwell-lt** [comment]
Added in version 1.14-2.0

d9b5602
