### ISSUE TITLE
forge always says an update is available

### ISSUE THREAD

**Issue by NyanMC** [Maxwell-lt/MobBlocker#39]
the green emerald in forge that indicates when one of your mods has an update is always visible. it always says that there is an update for Mob Blocker. this gets annoying when trying to update other mods. please fix this.

**Comment by Maxwell-lt** [comment]
What version are you using, and can you post a screenshot of the mod info page in Mod Options?

**Comment by NyanMC** [comment]
I'm updating forge to the latest version right now to see if it happens on the current version of forge. If the issue persists, I will post an image of it.

**Comment by NyanMC** [comment]
![minecraft 1 12 2 10_23_2018 7_43_08 pm](https://user-images.githubusercontent.com/44331238/47397159-f4620500-d6fb-11e8-84a6-6f92f84b7b4e.png)

**Comment by Maxwell-lt** [comment]
Can you check again and see if the issue is resolved? The version number that release has and what I put in the update.json were in disagreement, which was probably the source of your issue.

**Comment by NyanMC** [comment]
Yes, the issue fixed itself. Thanks.
