### ISSUE TITLE
protection issue

### ISSUE THREAD

**Issue by phantom1151** [Maxwell-lt/MobBlocker#40]
i place to chunk protector down and it seems to only work half way, it does not seem to protect the whole chunk but only like 4 block each way and sometime not at all. the area protector works just fine. it is in a mod pack with mob mods its not effecting even the base mobs. my modpack in called crimson adventures its a work in progress but it should be a good way for you to see the mob list instead of me typing them all in. it is a 1.12.2 pack

**Comment by Maxwell-lt** [comment]
Are you sure you're not mixing up the Chunk Protector and the Area Protector? I just tested this mod in Crimson Adventures 0.4 to see if it worked, and both blocks worked exactly as they should.
[Video of my test](https://www.youtube.com/watch?v=Gq9tFjhvlSQ)
In the above video, the glass blocks mark the effective range of the Protectors. A Chunk Protector removes mobs inside of the chunk it is placed in, from bedrock to the build limit, and regardless of where in the chunk it is placed (a 16x256x16 volume). The Area Protector removes mobs in a configurable area centered around itself, in this case 5 blocks in each direction (a 11x11x11 volume). The Area Protector does have a vertical limit for operation, unlike the Chunk Protector.

I'll reopen if you can provide a video of the behavior you mentioned, but for now it seems like a mix-up between the block types.
